# -*- coding: utf-8 -*-
"""irisproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HW9DCsC5iJzUut1LrIOGcFUl5_UZL82
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
# %matplotlib inline

colums = ['Sepal length','Sepal width','petal length','petal width','class_;abels']
df = pd.read_csv('iris.data',names=colums)
df.head(150)

df.describe()

"""# New Section"""

sns.pairplot(df, hue='Class_labels')

data = df.values
X = data[:,0:4]
Y = data[:,4]
print(X)

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
print(X_test)

from sklearn.svm import SVC
model = SVC()
model.fit(X_train, Y_train)

from sklearn.metrics import accuracy_score
predictions1 = model.predict(X_test)
print(accuracy_score(Y_test, predictions1))
for i in range(len(predictions1)):
  print(predictions[i], Y_test[i])

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, Y_train)

from sklearn.metrics import accuracy_score
predictions2 = model.predict(X_test)
print(accuracy_score(Y_test, predictions2)*100)
for i in range(len(predictions1)):
  print(predictions[i], Y_test[i])